apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: adityabhattad/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.py
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: adityabhattad/rag-uploader
      context: rag_uploader
      sync:
        manual:
          - src: src/**/*.py
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: adityabhattad/query-preprocessing
      context: query_preprocessing
      sync:
        manual:
          - src: src/**/*.py
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: adityabhattad/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'app/**/*.{js,ts,jsx,tsx,mdx}'
            dest: .
          - src: 'components/**/*.{js,ts,jsx,tsx,mdx}'
            dest: .
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
