apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-preprocessing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-preprocessing
  template:
    metadata:
      labels:
        app: query-preprocessing
    spec:
      initContainers:
        - name: wait-for-db
          image: pgvector/pgvector:pg16
          command:
            [
              'sh',
              '-c',
              'until pg_isready -h postgres-service -p 5432; do echo waiting for database; sleep 2; done;',
            ]
      containers:
        - name: query-preprocessing
          image: adityabhattad/query-preprocessing
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: GOOGLE_API_KEY
            - name: OLLAMA_URL
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: OLLAMA_URL
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: GROQ_API_KEY
            - name: CLAUDE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: CLAUDE_API_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: SECRET_KEY
            - name: ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: ALGORITHM
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: ACCESS_TOKEN_EXPIRE_MINUTES
            - name: TAVILY_AI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: TAVILY_AI_API_KEY
            - name: REDIS_HOST
              value: redis-service
            - name: CONNECTION_STRING
              value: 'postgresql+psycopg2://admin:admin@postgres-service:5432/vectordb'
            - name: CONNECTION_NAME
              value: 'vectordb'
---
apiVersion: v1
kind: Service
metadata:
  name: query-preprocessing-service
spec:
  selector:
    app: query-preprocessing
  type: ClusterIP
  ports:
    - name: query-preprocessing
      protocol: TCP
      port: 8000
      targetPort: 80
